/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/views/Account.vue')['default']
    Blueprint: typeof import('./src/components/blueprint/Blueprint.vue')['default']
    Card: typeof import('./src/components/commons/Card.vue')['default']
    DragFolder: typeof import('./src/components/commons/DragFolder.vue')['default']
    DragTree_Test: typeof import('./src/components/container/DragTree_Test.vue')['default']
    EchartCard: typeof import('./src/components/commons/EchartCard.vue')['default']
    ExcelEditor: typeof import('./src/components/commons/ExcelEditor.vue')['default']
    Excelmgmt: typeof import('./src/components/views/Excelmgmt.vue')['default']
    Excelupload_export: typeof import('./src/components/commons/excelupload_export.vue')['default']
    ExceluploadExport: typeof import('./src/components/commons/ExceluploadExport.vue')['default']
    ExcelUploadExport: typeof import('./src/components/commons/ExcelUploadExport.vue')['default']
    FileList: typeof import('./src/components/dragtree/FileList.vue')['default']
    FlieList: typeof import('./src/components/dragtree/FlieList.vue')['default']
    Footer: typeof import('./src/components/commons/PageFooter.vue')['default']
    FriendLinks: typeof import('./src/components/commons/FriendLinks.vue')['default']
    Home: typeof import('./src/components/views/Home.vue')['default']
    HomeEchart: typeof import('./src/components/echarts/HomeEchart.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    LinearDevelopmentLog: typeof import('./src/components/commons/LinearDevelopmentLog.vue')['default']
    Node: typeof import('./src/components/container/node.vue')['default']
    PageFooter: typeof import('./src/components/commons/PageFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNar: typeof import('./src/components/commons/SidebarNar.vue')['default']
    ThemSwitcher: typeof import('./src/components/commons/ThemSwitcher.vue')['default']
    TreeDrag: typeof import('./src/components/container/TreeDrag.vue')['default']
  }
}
